/*PERCENTILE_CONT AND PERCENTILE_DISC*/

SELECT DISTINCT EmployeeNumber
PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY NumberAttendance) OVER (PARTITION BY EmployeeNumber) AS AverageCont,
PERCENTILE_DISC(0.5) WITHIN GROUP(ORDER BY NumberAttendance) OVER (PARTITION BY EmployeeNumber) AS AverageDisc
FROM tblAttendance


    



/*PERCENTILE_CONT AND PERCENTILE_DISC*/